// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
	medicalMarket: string | null;
	medicAuthority: string | null;
	multisig: { ss58: string; h160: string; threshold: number; signatories: string[] } | null;
} = {
	medicalMarket: "0x368fe3c24df0c8493c718cafcb11f4294b2c42ef",
	medicAuthority: "0xa9d46878afbe943ae4c955048ed8ecba190530d3",
	multisig: {
		ss58: "5Drae25fn2KwZKuST7LCvB7D4rdyqFoMAdSD4CEdQPuQr2Lk",
		h160: "0x1597f37473220526382eb1a190a4fd97e7270648",
		threshold: 2,
		signatories: [
			"5Doa63xYuFXQaWkM5decEj7cgrr5eCcP5YbN4faTHvWdRdQs",
			"5HaLFkCjJyuUSnyoPKYukWksCKvy489QmiTKCiJUxoorpHvq",
			"5Hp3SxTNMvussku1zRRaFwn7waW4uHdhJUF61st9EZzXb8wd",
		],
	},
};
