// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
	evm: string | null;
	pvm: string | null;
	medicalMarket: string | null;
	medicAuthority: string | null;
	multisig: { ss58: string; h160: string; threshold: number; signatories: string[] } | null;
} = {
	evm: "0xc01ee7f10ea4af4673cfff62710e1d7792aba8f3",
	pvm: "0x970951a12f975e6762482aca81e57d5a2a4e73f4",
	medicalMarket: "0x3ed62137c5db927cb137c26455969116bf0c23cb",
	medicAuthority: "0x962c0940d72e7db6c9a5f81f1ca87d8db2b82a23",
	multisig: {
		ss58: "5DjYJStmdZ2rcqXbXGX7TW85JsrW6uG4y9MUcLq2BoPMpRA7",
		h160: "0x9549ff5910afff47319cba6acd90c683278f267f",
		threshold: 2,
		signatories: [
			"5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
			"5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y",
			"5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
		],
	},
};
