import * as fs from "fs";
import * as path from "path";
import {
	createWalletClient,
	createPublicClient,
	http,
	defineChain,
	type Chain,
	type Hex,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

// Compiled artifacts — produced by `cargo build --release` inside contracts/pvm/
const TARGET_DIR = path.resolve(__dirname, "../../../target");
const POLKAVM_BLOB = path.join(TARGET_DIR, "dot-transfer.release.polkavm");
const ABI_JSON = path.join(TARGET_DIR, "dot-transfer.release.abi.json");

const local = defineChain({
	id: 420420421,
	name: "Local Dev",
	nativeCurrency: { name: "WND", symbol: "WND", decimals: 18 },
	rpcUrls: { default: { http: [process.env.ETH_RPC_HTTP ?? "http://127.0.0.1:8545"] } },
});

const paseoAssetHub = defineChain({
	id: 420420417,
	name: "Paseo Asset Hub",
	nativeCurrency: { name: "PAS", symbol: "PAS", decimals: 10 },
	rpcUrls: {
		default: { http: ["https://eth-rpc-testnet.polkadot.io/"] },
	},
});

function getNetwork(): { chain: Chain; privateKey: Hex } {
	const network = process.env.NETWORK ?? "local";
	if (network === "paseo") {
		const key = process.env.PRIVATE_KEY;
		if (!key) throw new Error("PRIVATE_KEY env var required for Paseo deployment");
		return { chain: paseoAssetHub, privateKey: key as Hex };
	}
	return {
		chain: local,
		// Alice well-known dev account
		privateKey: "0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133",
	};
}

function updateDeployments(key: string, address: string) {
	let data: Record<string, string | null> = {};
	try {
		data = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
	} catch {
		// file doesn't exist yet
	}
	data[key] = address;

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const tsKeysType = Object.keys(data)
		.map(k => `${k}: string | null`)
		.join("; ");
	const tsLines = Object.entries(data)
		.map(([k, v]) => `\t${k}: ${fmt(v)},`)
		.join("\n");
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { ${tsKeysType} } = {
${tsLines}
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	if (!fs.existsSync(POLKAVM_BLOB)) {
		throw new Error(
			`Compiled artifact not found: ${POLKAVM_BLOB}\nRun: cd contracts/pvm && cargo build --release`,
		);
	}

	const bytecodeBuffer = fs.readFileSync(POLKAVM_BLOB);
	const bytecode: Hex = `0x${bytecodeBuffer.toString("hex")}`;

	const abi = JSON.parse(fs.readFileSync(ABI_JSON, "utf-8"));

	const { chain, privateKey } = getNetwork();
	const account = privateKeyToAccount(privateKey);

	const walletClient = createWalletClient({ account, chain, transport: http() });
	const publicClient = createPublicClient({ chain, transport: http() });

	console.log(`Deploying DotTransfer to ${chain.name} as ${account.address}...`);

	const hash = await walletClient.deployContract({ abi, bytecode });
	console.log(`  tx: ${hash}`);

	const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 120_000 });
	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	console.log(`DotTransfer deployed to: ${receipt.contractAddress}`);
	updateDeployments("dotTransfer", receipt.contractAddress);
	console.log("Updated deployments.json");
}

main().catch(err => {
	console.error(err);
	process.exitCode = 1;
});
