import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

export type DeploymentsShape = {
	evm: string | null;
	pvm: string | null;
	medicalMarket: string | null;
	verifier: string | null;
	medicAuthority: string | null;
	multisig: {
		ss58: string;
		h160: string;
		threshold: number;
		signatories: string[];
	} | null;
};

const EMPTY: DeploymentsShape = {
	evm: null,
	pvm: null,
	medicalMarket: null,
	verifier: null,
	medicAuthority: null,
	multisig: null,
};

export function readDeployments(): DeploymentsShape {
	try {
		const raw = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
		return { ...EMPTY, ...raw };
	} catch {
		return { ...EMPTY };
	}
}

export function updateDeployments(updates: Partial<DeploymentsShape>): void {
	const data: DeploymentsShape = { ...readDeployments(), ...updates };

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const fmtMultisig = (v: DeploymentsShape["multisig"]) => {
		if (v === null) return "null";
		const sigs = v.signatories.map((s) => `\t\t\t"${s}"`).join(",\n");
		return `{
\t\tss58: "${v.ss58}",
\t\th160: "${v.h160}",
\t\tthreshold: ${v.threshold},
\t\tsignatories: [
${sigs},
\t\t],
\t}`;
	};

	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
\tevm: string | null;
\tpvm: string | null;
\tmedicalMarket: string | null;
\tverifier: string | null;
\tmedicAuthority: string | null;
\tmultisig: { ss58: string; h160: string; threshold: number; signatories: string[] } | null;
} = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tmedicalMarket: ${fmt(data.medicalMarket)},
\tverifier: ${fmt(data.verifier)},
\tmedicAuthority: ${fmt(data.medicAuthority)},
\tmultisig: ${fmtMultisig(data.multisig)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}
