import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

function updateDeployments(updates: Record<string, string>) {
	let data: Record<string, string | null> = {
		evm: null,
		pvm: null,
		medicalMarket: null,
		verifier: null,
	};
	try {
		data = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
	} catch {
		// File doesn't exist yet
	}
	for (const [key, address] of Object.entries(updates)) {
		data[key] = address;
	}

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
\tevm: string | null;
\tpvm: string | null;
\tmedicalMarket: string | null;
\tverifier: string | null;
} = {
\tevm: ${fmt(data.evm ?? null)},
\tpvm: ${fmt(data.pvm ?? null)},
\tmedicalMarket: ${fmt(data.medicalMarket ?? null)},
\tverifier: ${fmt(data.verifier ?? null)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function deployContract(
	walletClient: Awaited<ReturnType<typeof hre.viem.getWalletClients>>[number],
	publicClient: Awaited<ReturnType<typeof hre.viem.getPublicClient>>,
	artifactName: string,
	args: unknown[] = [],
): Promise<string> {
	const artifact = await hre.artifacts.readArtifact(artifactName);
	const hash = await walletClient.deployContract({
		abi: artifact.abi,
		bytecode: artifact.bytecode as `0x${string}`,
		args,
		maxPriorityFeePerGas: 10n,
	});
	const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 120_000 });
	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} for ${artifactName} did not create a contract`);
	}
	return receipt.contractAddress;
}

async function main() {
	const [walletClient] = await hre.viem.getWalletClients();
	const publicClient = await hre.viem.getPublicClient();

	console.log("Deploying Verifier (PVM/resolc)...");
	const verifierAddress = await deployContract(walletClient, publicClient, "Verifier");
	console.log(`Verifier deployed to: ${verifierAddress}`);

	console.log("Deploying MedicalMarket (PVM/resolc)...");
	const marketAddress = await deployContract(walletClient, publicClient, "MedicalMarket", [
		verifierAddress,
	]);
	console.log(`MedicalMarket deployed to: ${marketAddress}`);

	updateDeployments({ medicalMarket: marketAddress, verifier: verifierAddress });
	console.log("Updated deployments.json and web/src/config/deployments.ts");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
